version: '3.8'

services:
   wordpress:
     image: wordpress:php7.4-fpm-alpine
     deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
     environment:
       WORDPRESS_DB_HOST:
       WORDPRESS_DB_USER:
       WORDPRESS_DB_PASSWORD:
       WORDPRESS_DB_NAME:
     volumes:
      - wordpress_data:/var/www/html
     networks:
       - internal
     configs:
      - source: wordpress_php_ini
        target: /usr/local/etc/php/php.ini
        uid: '0'
        gid: '0'
        mode: 0444
      - source: wordpress_php_fpm_www_conf
        target: /usr/local/etc/php-fpm.d/www.conf
        uid: '0'
        gid: '0'
        mode: 0444   
        
   nginx:
    image: nginx:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - wordpress_data:/var/www/html
    networks:
     - internal
     - nlb_ingress
    configs:
      - source: wordpress_nginx_conf
        target: /etc/nginx/conf.d/default.conf
        uid: '0'
        gid: '0'
        mode: 0444 

volumes:
  wordpress_data:

networks:
  nlb_ingress:
    external: true
  internal:
  
configs:
  wordpress_nginx_conf:
    external: true
  wordpress_php_fpm_www_conf:
    external: true
  wordpress_php_ini:
    external: true
